name: ggecl-app

services:
  redis:
    image: redis:8.0-M03
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
    networks:
      - ggecl-app

  redis_insight:
    image: redis/redisinsight:latest
    restart: unless-stopped
    ports:
      - 5540:5540
    volumes:
      - redis_insight_data:/data/db
    networks:
      - ggecl-app

  mongo:
    image: mongo:8.0
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - ggecl-app

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - ggecl-app
    ports:
      - 4000:4000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
    depends_on:
      - mongo
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - ggecl-app
    ports:
      - 5173:5173
    command: npm run dev -- --host
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
    depends_on:
      - api

volumes:
  mongo_data:
  redis_data:
  redis_insight_data:

networks:
  ggecl-app:
    driver: bridge
